/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ir.kukuapp.mobile;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int button=0x7f020000;
        public static final int button_disabled=0x7f020001;
        public static final int button_enabled=0x7f020002;
        public static final int button_focused=0x7f020003;
        public static final int button_pressed=0x7f020004;
        public static final int card=0x7f020005;
        public static final int logo=0x7f020006;
    }
    public static final class id {
        public static final int btn_login=0x7f06000a;
        public static final int btn_logout=0x7f060004;
        public static final int btn_refresh=0x7f060003;
        public static final int btn_send=0x7f060001;
        public static final int et_password=0x7f060009;
        public static final int et_status=0x7f060000;
        public static final int et_username=0x7f060007;
        public static final int imageView=0x7f060005;
        public static final int list_home=0x7f060002;
        public static final int textView=0x7f060006;
        public static final int textView2=0x7f060008;
        public static final int tv_status=0x7f06000b;
    }
    public static final class layout {
        public static final int activity_home=0x7f030000;
        public static final int activity_login=0x7f030001;
        public static final int listitem_home=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int login=0x7f040003;
        public static final int logout=0x7f040004;
        public static final int menu_settings=0x7f040001;
        public static final int password=0x7f040008;
        public static final int refresh=0x7f040009;
        public static final int send=0x7f040005;
        public static final int title_activity_main=0x7f040002;
        public static final int userid=0x7f040007;
        public static final int username=0x7f040006;
    }
    public static final class style {
        public static final int AppBaseTheme=0x7f050000;
        public static final int AppTheme=0x7f050001;
        /**  Details 
         */
        public static final int button=0x7f050002;
    }
}
